$(function(){$('.nav > li').hover(function(){var sec_count=$(this).find('.sec a').length;var a_height=$(this).find('.sec a').eq(0).height();var sec_height=sec_count*a_height;$(this).find('.sec').stop().animate({height:sec_height},300);},function(){$(this).find('.sec').stop().animate({height:0},300);});$(".hd .sjdh").click(function(){$(".sjdd").slideToggle(100);});});$(window).scroll(function(){var bodyTop=0,sideTop=$('.hd  #menu').eq(0).height()+0;if(typeof window.pageYOffset!='undefined'){bodyTop=window.pageYOffset;}else if(typeof document.compatMode!='undefined'&&document.compatMode!='BackCompat'){bodyTop=document.documentElement.scrollTop;}else if(typeof document.body!='undefined'){bodyTop=document.body.scrollTop;}
if(bodyTop>sideTop){$('.hd').css({'position':'fixed','top':'0','z-index':'99'});}else{$('.hd').css({position:'relative'});}});jQuery(document).ready(function($){var sweetTitles={x:10,y:20,tipElements:"a,span,img,div ",noTitle:false,init:function(){var noTitle=this.noTitle;$(this.tipElements).each(function(){$(this).mouseover(function(e){if(noTitle){isTitle=true;}else{isTitle=$.trim(this.title)!='';}
if(isTitle){this.myTitle=this.title;this.title="";var tooltip="<div class='tooltip'><div class='tipsy-arrow tipsy-arrow-n'></div><div class='tipsy-inner'>"+this.myTitle+"</div></div>";$('body').append(tooltip);$('.tooltip').css({"top":(e.pageY+20)+"px","left":(e.pageX-20)+"px"}).show('fast');}}).mouseout(function(){if(this.myTitle!=null){this.title=this.myTitle;$('.tooltip').remove();}}).mousemove(function(e){$('.tooltip').css({"top":(e.pageY+20)+"px","left":(e.pageX-20)+"px"});});});}};$(function(){sweetTitles.init();});});(function($,window,document,undefined){var $window=$(window);$.fn.lazyload=function(options){var elements=this;var $container;var settings={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:window,data_attribute:"original",skip_invisible:true,appear:null,load:null,placeholder:"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC"};function update(){var counter=0;elements.each(function(){var $this=$(this);if(settings.skip_invisible&&!$this.is(":visible")){return;}
if($.abovethetop(this,settings)||$.leftofbegin(this,settings)){}else if(!$.belowthefold(this,settings)&&!$.rightoffold(this,settings)){$this.trigger("appear");counter=0;}else{if(++counter>settings.failure_limit){return false;}}});}
if(options){if(undefined!==options.failurelimit){options.failure_limit=options.failurelimit;delete options.failurelimit;}
if(undefined!==options.effectspeed){options.effect_speed=options.effectspeed;delete options.effectspeed;}
$.extend(settings,options);}
$container=(settings.container===undefined||settings.container===window)?$window:$(settings.container);if(0===settings.event.indexOf("scroll")){$container.bind(settings.event,function(){return update();});}
this.each(function(){var self=this;var $self=$(self);self.loaded=false;if($self.attr("src")===undefined||$self.attr("src")===false){if($self.is("img")){$self.attr("src",settings.placeholder);}}
$self.one("appear",function(){if(!this.loaded){if(settings.appear){var elements_left=elements.length;settings.appear.call(self,elements_left,settings);}
$("<img />").bind("load",function(){var original=$self.attr("data-"+settings.data_attribute);$self.hide();if($self.is("img")){$self.attr("src",original);}else{$self.css("background-image","url('"+original+"')");}
$self[settings.effect](settings.effect_speed);self.loaded=true;var temp=$.grep(elements,function(element){return!element.loaded;});elements=$(temp);if(settings.load){var elements_left=elements.length;settings.load.call(self,elements_left,settings);}}).attr("src",$self.attr("data-"+settings.data_attribute));}});if(0!==settings.event.indexOf("scroll")){$self.bind(settings.event,function(){if(!self.loaded){$self.trigger("appear");}});}});$window.bind("resize",function(){update();});if((/(?:iphone|ipod|ipad).*os 5/gi).test(navigator.appVersion)){$window.bind("pageshow",function(event){if(event.originalEvent&&event.originalEvent.persisted){elements.each(function(){$(this).trigger("appear");});}});}
$(document).ready(function(){update();});return this;};$.belowthefold=function(element,settings){var fold;if(settings.container===undefined||settings.container===window){fold=(window.innerHeight?window.innerHeight:$window.height())+$window.scrollTop();}else{fold=$(settings.container).offset().top+$(settings.container).height();}
return fold<=$(element).offset().top-settings.threshold;};$.rightoffold=function(element,settings){var fold;if(settings.container===undefined||settings.container===window){fold=$window.width()+$window.scrollLeft();}else{fold=$(settings.container).offset().left+$(settings.container).width();}
return fold<=$(element).offset().left-settings.threshold;};$.abovethetop=function(element,settings){var fold;if(settings.container===undefined||settings.container===window){fold=$window.scrollTop();}else{fold=$(settings.container).offset().top;}
return fold>=$(element).offset().top+settings.threshold+$(element).height();};$.leftofbegin=function(element,settings){var fold;if(settings.container===undefined||settings.container===window){fold=$window.scrollLeft();}else{fold=$(settings.container).offset().left;}
return fold>=$(element).offset().left+settings.threshold+$(element).width();};$.inviewport=function(element,settings){return!$.rightoffold(element,settings)&&!$.leftofbegin(element,settings)&&!$.belowthefold(element,settings)&&!$.abovethetop(element,settings);};$.extend($.expr[":"],{"below-the-fold":function(a){return $.belowthefold(a,{threshold:0});},"above-the-top":function(a){return!$.belowthefold(a,{threshold:0});},"right-of-screen":function(a){return $.rightoffold(a,{threshold:0});},"left-of-screen":function(a){return!$.rightoffold(a,{threshold:0});},"in-viewport":function(a){return $.inviewport(a,{threshold:0});},"above-the-fold":function(a){return!$.belowthefold(a,{threshold:0});},"right-of-fold":function(a){return $.rightoffold(a,{threshold:0});},"left-of-fold":function(a){return!$.rightoffold(a,{threshold:0});}});})(jQuery,window,document);jQuery(document).ready(function($){var sweetTitles={x:10,y:20,tipElements:"a,span,img,div ",noTitle:false,init:function(){var noTitle=this.noTitle;$(this.tipElements).each(function(){$(this).mouseover(function(e){if(noTitle){isTitle=true;}else{isTitle=$.trim(this.title)!='';}
if(isTitle){this.myTitle=this.title;this.title="";var tooltip="<div class='tooltip'><div class='tipsy-arrow tipsy-arrow-n'></div><div class='tipsy-inner'>"+this.myTitle+"</div></div>";$('body').append(tooltip);$('.tooltip').css({"top":(e.pageY+20)+"px","left":(e.pageX-20)+"px"}).show('fast');}}).mouseout(function(){if(this.myTitle!=null){this.title=this.myTitle;$('.tooltip').remove();}}).mousemove(function(e){$('.tooltip').css({"top":(e.pageY+20)+"px","left":(e.pageX-20)+"px"});});});}};$(function(){sweetTitles.init();});});$(function(){var e=$("#rocket-to-top"),t=$(document).scrollTop(),n,r,i=!0;$(window).scroll(function(){var t=$(document).scrollTop();t==0?e.css("background-position")=="0px 0px"?e.fadeOut("slow"):i&&(i=!1,$(".level-2").css("opacity",1),e.delay(100).animate({marginTop:"-1000px"},"normal",function(){e.css({"margin-top":"-125px",display:"none"}),i=!0})):e.fadeIn("slow")}),e.hover(function(){$(".level-2").stop(!0).animate({opacity:1})},function(){$(".level-2").stop(!0).animate({opacity:0})}),$(".level-3").click(function(){function t(){var t=e.css("background-position");if(e.css("display")=="none"||i==0){clearInterval(n),e.css("background-position","0px 0px");return}
switch(t){case"0px 0px":e.css("background-position","-298px 0px");break;case"-298px 0px":e.css("background-position","-447px 0px");break;case"-447px 0px":e.css("background-position","-596px 0px");break;case"-596px 0px":e.css("background-position","-745px 0px");break;case"-745px 0px":e.css("background-position","-298px 0px");}}
if(!i)return;n=setInterval(t,50),$("html,body").animate({scrollTop:0},"slow");});});